packages:
  - "apps/*"
  - "backend/*"
  - "packages/*"
  - "mobile/*"

publicHoistPattern:
  - "*expo*"
  - "*expo-modules-core*"
  - "*expo-modules-autolinking*"
  - "*babel-preset-expo*"
  - "*@expo/*"
  - "*react-native*"
  - "*@react-native*/*"
