ALTER TABLE "business_settings" ADD COLUMN IF NOT EXISTS "seoConfig" JSONB;

ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "seoTitle" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "seoDescription" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "imageAltText" TEXT;

ALTER TABLE "seo_metadata" ADD COLUMN IF NOT EXISTS "noIndex" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "seo_metadata" ADD COLUMN IF NOT EXISTS "noFollow" BOOLEAN NOT NULL DEFAULT false;
