/**
 * Production-safe defaults used when remote config is temporarily unavailable.
 * Keeps the app bootable on first launch / poor connectivity.
 */
import type { MobileAppConfigDto } from '@mdh/types';
import { API_URL } from './constants';

export const DEFAULT_APP_CONFIG: MobileAppConfigDto = {
  configVersion: 0,
  updatedAt: new Date(0).toISOString(),
  refreshIntervalSeconds: 300,
  apiBaseUrl: API_URL,
  branding: {
    appName: 'Mercy Dosa House',
    tagline: 'Crispy Dosas. Happy Hearts.',
    logoUrl: null,
    splashLogoUrl: null,
    splashBackgroundColor: '#14532D',
    splashBackgroundImageUrl: null,
    appIconUrl: null,
  },
  theme: {
    primaryColor: '#14532D',
    secondaryColor: '#F59E0B',
    fontFamily: 'Inter',
    borderRadius: '12px',
    darkModeDefault: false,
    allowDarkMode: true,
    allowLightMode: true,
  },
  maintenance: {
    maintenanceMode: false,
    maintenanceMessage: null,
    maintenanceEndsAt: null,
  },
  versionControl: {
    minAppVersion: '1.0.0',
    latestAppVersion: '1.0.8',
    forceUpdate: false,
    softUpdateMessage: null,
  },
  store: {
    storeOpen: true,
    storeClosedMessage: null,
    emergencyNotice: null,
    openingHours: '7:00 AM - 10:00 PM',
    deliveryHours: null,
  },
  delivery: {
    deliveryCharge: 30,
    packingCharge: 10,
    minOrderAmount: 99,
    freeDeliveryLimit: 299,
    deliveryRadiusKm: 10,
    estimatedDeliveryMinutes: 30,
    preOrderDiscountPct: 10,
    preOrderMinDaysAhead: 1,
    preOrderStackWithCoupons: false,
  },
  business: {
    businessName: 'Mercy Dosa House',
    phone: '9563636365',
    whatsapp: '919563636365',
    email: 'info@mercydosahouse.com',
    address: 'Tura, Meghalaya',
    upiId: null,
  },
  homepage: [
    {
      id: 'default-hero',
      sectionKey: 'hero_banner',
      title: 'Hero',
      content: { title: 'Mercy Dosa House', subtitle: 'Fresh dosas delivered to your door' },
      sortOrder: 1,
      isEnabled: true,
      status: 'PUBLISHED',
    },
    {
      id: 'default-categories',
      sectionKey: 'categories',
      title: 'Categories',
      content: {},
      sortOrder: 2,
      isEnabled: true,
      status: 'PUBLISHED',
    },
    {
      id: 'default-popular',
      sectionKey: 'popular_items',
      title: 'Popular Items',
      content: {},
      sortOrder: 3,
      isEnabled: true,
      status: 'PUBLISHED',
    },
  ],
  announcements: [],
  offers: [],
  banners: [],
  navigation: [],
  featureFlags: {
    reviews: true,
    ratings: true,
    wishlist: true,
    loyalty: true,
    referral: false,
    coupons: true,
    scheduled_orders: true,
    pre_order_discount: true,
    live_tracking: false,
    whatsapp_support: true,
    chat: false,
    push_notifications: false,
    google_login: false,
    guest_checkout: true,
  },
  paymentMethods: [
    { method: 'COD', isEnabled: true, config: null },
    { method: 'UPI', isEnabled: false, config: null },
    { method: 'RAZORPAY', isEnabled: false, config: null },
  ],
  help: {
    faqs: [],
    whatsapp: '919563636365',
    phone: '9563636365',
    email: 'info@mercydosahouse.com',
  },
};
